[package]
name = "baremp3"
version = "0.1.0"
edition = "2024"

[dependencies]
bitreader = "0.3.11"
hound = "3.5.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "decode_benchmark"
harness = false
